server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://116.205.233.28:3306/examination?connectionTimeZone=Asia/Shanghai&forceConnectionTimeZoneToSession=true
    username: examination
    password: BySootNYdwVn3Jg6
  redis:
    host: 116.205.233.28
    port: 6379
    username: default
    password: YS8OYDtcLFAsQ5Xb
minio:
  https: false
  host: 116.205.233.28
  port: 9000
  access-key: LsmHvWcnBql2ExK7uqyN
  secret-key: r33dUvhtk1k6z7zgCw3TzPDbO16A9z7rrUCOv0ws
wechat:
  pay:
    v3:
      pc:
        app-id: wx4cb8e9621950da45
        app-v3-secret: b693aee4bdfb4080b93832d90b41e270
        mch-id: 1526972031
        domain: https://49e0b218.r1.cpolar.top
        cert-path: apiclient_cert.p12
