server:
  port: 80
sa-token:
  is-print: false
  token-name: token
  jwt-secret-key: 8T4AkqkzJVFfCnn7uNBvsRsfU5BQ5xnT
  is-read-cookie: false
  is-read-body: false
dubbo:
  application:
    name: examination-api
    qos-port: 22000
    serialize-check-status: DISABLE
  protocol:
    name: dubbo
    port: 9100
  registry:
    address: nacos://127.0.0.1:8848