spring:
  rabbitmq:
    host: 116.205.233.28
    port: 5672
    username: guest
    password: guest
    virtual-host: /
dubbo:
  application:
    name: examination-payment
    qos-port: 22006
  protocol:
    name: dubbo
    port: 9106
  registry:
    address: nacos://127.0.0.1:8848
